<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle-01-numpy-and-matplotlib-iris-Chouss777/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :  
Filière :  
Année universitaire :

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
data = np.genfromtxt('Iris.csv' , delimiter=',' , skip_header=1, dtype= object)
print(data.shape)


(150, 6)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [2]:
features = data[: , :4].astype(float)
species = data[: , 4]


### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [3]:
print(features[:5])


[[1.  5.1 3.5 1.4]
 [2.  4.9 3.  1.4]
 [3.  4.7 3.2 1.3]
 [4.  4.6 3.1 1.5]
 [5.  5.  3.6 1.4]]


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [4]:
sepal_length = features[: , 0]
print("size :", sepal_length.size)
print("dtype:", sepal_length.dtype)

size : 150
dtype: float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [6]:
setosa_features = features[:50]
print(setosa_features)


[[ 1.   5.1  3.5  1.4]
 [ 2.   4.9  3.   1.4]
 [ 3.   4.7  3.2  1.3]
 [ 4.   4.6  3.1  1.5]
 [ 5.   5.   3.6  1.4]
 [ 6.   5.4  3.9  1.7]
 [ 7.   4.6  3.4  1.4]
 [ 8.   5.   3.4  1.5]
 [ 9.   4.4  2.9  1.4]
 [10.   4.9  3.1  1.5]
 [11.   5.4  3.7  1.5]
 [12.   4.8  3.4  1.6]
 [13.   4.8  3.   1.4]
 [14.   4.3  3.   1.1]
 [15.   5.8  4.   1.2]
 [16.   5.7  4.4  1.5]
 [17.   5.4  3.9  1.3]
 [18.   5.1  3.5  1.4]
 [19.   5.7  3.8  1.7]
 [20.   5.1  3.8  1.5]
 [21.   5.4  3.4  1.7]
 [22.   5.1  3.7  1.5]
 [23.   4.6  3.6  1. ]
 [24.   5.1  3.3  1.7]
 [25.   4.8  3.4  1.9]
 [26.   5.   3.   1.6]
 [27.   5.   3.4  1.6]
 [28.   5.2  3.5  1.5]
 [29.   5.2  3.4  1.4]
 [30.   4.7  3.2  1.6]
 [31.   4.8  3.1  1.6]
 [32.   5.4  3.4  1.5]
 [33.   5.2  4.1  1.5]
 [34.   5.5  4.2  1.4]
 [35.   4.9  3.1  1.5]
 [36.   5.   3.2  1.2]
 [37.   5.5  3.5  1.3]
 [38.   4.9  3.1  1.5]
 [39.   4.4  3.   1.3]
 [40.   5.1  3.4  1.5]
 [41.   5.   3.5  1.3]
 [42.   4.5  2.3  1.3]
 [43.   4.4  3.2  1.3]
 [44.   5. 

# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [7]:
moyennes = np.mean(features , axis=0)
print(moyennes)

[75.5         5.84333333  3.054       3.75866667]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [8]:
petal_length = features [:, 2]
print ("Valeur minimale :", petal_length.min())
print ("Valeur maximale :", petal_length.max())


Valeur minimale : 2.0
Valeur maximale : 4.4


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [9]:
normalized_petals = petal_length / petal_length.max()
print(normalized_petals)


[0.79545455 0.68181818 0.72727273 0.70454545 0.81818182 0.88636364
 0.77272727 0.77272727 0.65909091 0.70454545 0.84090909 0.77272727
 0.68181818 0.68181818 0.90909091 1.         0.88636364 0.79545455
 0.86363636 0.86363636 0.77272727 0.84090909 0.81818182 0.75
 0.77272727 0.68181818 0.77272727 0.79545455 0.77272727 0.72727273
 0.70454545 0.77272727 0.93181818 0.95454545 0.70454545 0.72727273
 0.79545455 0.70454545 0.68181818 0.77272727 0.79545455 0.52272727
 0.72727273 0.79545455 0.86363636 0.68181818 0.86363636 0.72727273
 0.84090909 0.75       0.72727273 0.72727273 0.70454545 0.52272727
 0.63636364 0.63636364 0.75       0.54545455 0.65909091 0.61363636
 0.45454545 0.68181818 0.5        0.65909091 0.65909091 0.70454545
 0.68181818 0.61363636 0.5        0.56818182 0.72727273 0.63636364
 0.56818182 0.63636364 0.65909091 0.68181818 0.63636364 0.68181818
 0.65909091 0.59090909 0.54545455 0.54545455 0.61363636 0.61363636
 0.68181818 0.77272727 0.70454545 0.52272727 0.68181818 0.56818182
 

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [10]:
versicolor_petal_width = features[50:100, 3]
cumsum_width = np.cumsum(versicolor_petal_width)
print(cumsum_width[:10])


[ 4.7  9.2 14.1 18.1 22.7 27.2 31.9 35.2 39.8 43.7]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [11]:
versicolor_petal_width = features[50:100, 3]
cumsum_width = np.cumsum(versicolor_petal_width)
print(cumsum_width[:10])


[ 4.7  9.2 14.1 18.1 22.7 27.2 31.9 35.2 39.8 43.7]


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [12]:
unique_species, counts = np.unique(species, return_counts=True)
print("espèces :", unique_species)
print("occurrences :", counts)


espèces : [b'0.1' b'0.2' b'0.3' b'0.4' b'0.5' b'0.6' b'1.0' b'1.1' b'1.2' b'1.3'
 b'1.4' b'1.5' b'1.6' b'1.7' b'1.8' b'1.9' b'2.0' b'2.1' b'2.2' b'2.3'
 b'2.4' b'2.5']
occurrences : [ 6 28  7  7  1  1  7  3  5 13  8 12  4  2 12  5  6  6  3  8  3  3]


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [13]:
features_by_species = features.reshape(3, 50, 4)


### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [14]:
moyennes = np.mean(features, axis=0)
zeros = np.zeros_like(moyennes)

concat = np.hstack([moyennes, zeros])
print(concat)


[75.5         5.84333333  3.054       3.75866667  0.          0.
  0.          0.        ]


### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [15]:
features_nan = features.copy().astype(float)

np.random.seed(0)
mask = np.random.choice([True, False], size=features_nan.shape, p=[0.05, 0.95])
features_nan[mask] = np.nan

features_clean = np.nan_to_num(features_nan, nan=0.0)  # NaN -> 0.0

### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [16]:
features[:, 0] += 1


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [17]:
petal_length = features[:, 2]
binary_mask = (petal_length > 4.0).astype(int)
print(binary_mask)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [ ]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [ ]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [ ]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [ ]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [ ]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [ ]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [ ]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [ ]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [ ]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [ ]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [ ]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...